name: prueba_unplash_gallery
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^6.2.1
  http: ^0.13.4
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.3.0
  path_provider: ^2.0.9

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mockito: ^5.3.2

flutter:
  uses-material-design: true
